
-- Definition for table tb_roles_details 

DROP TABLE IF EXISTS tb_roles_details;
CREATE TABLE tb_roles_details (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL DEFAULT '',
  DESCRIPTION VARCHAR(200) DEFAULT NULL,
  STATUS VARCHAR(35) NOT NULL DEFAULT '',
  UPDATED_BY VARCHAR(50) NOT NULL DEFAULT '',
  UPDATED_DT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (ID),
  UNIQUE INDEX NAME (NAME)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 4096
CHARACTER SET latin1
COLLATE latin1_swedish_ci;



--
-- Definition for table tb_users_details
--
DROP TABLE IF EXISTS tb_users_details;
CREATE TABLE tb_users_details (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(50) NOT NULL DEFAULT '',
  EMPLOYEE_NAME VARCHAR(200) NOT NULL DEFAULT '',
  ROLE_ID INT(10) UNSIGNED NOT NULL DEFAULT 0,
  STATUS_ID VARCHAR(35) NOT NULL DEFAULT '',
  EMAIL_ID VARCHAR(150) NOT NULL DEFAULT '',
  EMPLOYEE_TYPE VARCHAR(50) NOT NULL DEFAULT '',
  MOBILE_NO VARCHAR(25) NOT NULL DEFAULT '',
  NO_OF_BAD_LOGINS INT(10) UNSIGNED DEFAULT 0,
  LASTLOGIN_DT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  UPDATED_BY VARCHAR(50) NOT NULL DEFAULT '',
  UPDATED_DT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (ID, USER_NAME),
  CONSTRAINT FK_TB_USERS_DETAILS_1 FOREIGN KEY (ROLE_ID)
    REFERENCES tb_roles_details(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 1260
CHARACTER SET latin1
COLLATE latin1_swedish_ci;




--
-- Definition for table tb_parent_features
--
DROP TABLE IF EXISTS tb_parent_features;
CREATE TABLE tb_parent_features (
  ID DECIMAL(10, 0) UNSIGNED NOT NULL DEFAULT 0,
  NAME VARCHAR(25) NOT NULL DEFAULT '',
  DESCRIPTION VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 5461
CHARACTER SET latin1
COLLATE latin1_swedish_ci;





--
-- Definition for table tb_child_features
--
DROP TABLE IF EXISTS tb_child_features;
CREATE TABLE tb_child_features (
  ID DECIMAL(10, 0) UNSIGNED NOT NULL DEFAULT 0,
  PARENT_FEATURE_ID DECIMAL(10, 0) NOT NULL DEFAULT 0,
  NAME VARCHAR(25) NOT NULL DEFAULT '',
  DESCRIPTION VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET latin1
COLLATE latin1_swedish_ci;




--
-- Definition for table tb_role_rights
--
DROP TABLE IF EXISTS tb_role_rights;
CREATE TABLE tb_role_rights (
  id INT(11) NOT NULL AUTO_INCREMENT,
  ROLE_ID INT(10) UNSIGNED NOT NULL,
  PARENT_FEATURE_ID DECIMAL(10, 0) NOT NULL DEFAULT 0,
  WRITE_RIGHTS INT(10) NOT NULL,
  UPDATED_BY VARCHAR(50) NOT NULL DEFAULT '',
  UPDATED_DT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id),
  CONSTRAINT FK_tb_role_rights_1 FOREIGN KEY (ROLE_ID)
    REFERENCES tb_roles_details(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_tb_role_rights_2 FOREIGN KEY (PARENT_FEATURE_ID)
    REFERENCES tb_parent_features(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 4096
CHARACTER SET latin1
COLLATE latin1_swedish_ci;




--
-- Definition for table tb_transactions_staging
--
DROP TABLE IF EXISTS tb_transactions_staging;
CREATE TABLE tb_transactions_staging (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  SR_NO VARCHAR(250) DEFAULT NULL,
  DATE DATE DEFAULT NULL,
  MEMBER_ME VARCHAR(250) DEFAULT NULL,
  CONSUMER_ME VARCHAR(250) DEFAULT NULL,
  ACCOUNT_NUMBER VARCHAR(250) DEFAULT NULL,
  ACCOUNT_TO_BE_SUPPRESSED VARCHAR(250) DEFAULT NULL,
  STATUS VARCHAR(35) DEFAULT NULL,
  COMMENTS TEXT DEFAULT NULL,
  OWNERSHIP_INDICATOR VARCHAR(250) DEFAULT NULL,
  ACCOUNT_TYPE VARCHAR(250) DEFAULT NULL,
  CURRENT_BALANCE VARCHAR(250) DEFAULT NULL,
  AMOUNT_OVERDUE VARCHAR(250) DEFAULT NULL,
  DATE_CLOSED DATE DEFAULT NULL,
  DATE_OF_LAST_PAYMENT DATE DEFAULT NULL,
  DATE_REPORTED DATE DEFAULT NULL,
  SACTIONED_AMOUNT VARCHAR(250) DEFAULT NULL,
  NDPD_FOR_LATEST_MONTH VARCHAR(250) DEFAULT NULL,
  ACCOUNT_STATUS VARCHAR(250) DEFAULT NULL,
  OTHERS VARCHAR(2000) DEFAULT NULL,
  RESPONSE VARCHAR(2000) DEFAULT NULL,
  DATE_PROCESSED DATE DEFAULT NULL,
  METHOD VARCHAR(250) DEFAULT NULL,
  MEMBER_CODE VARCHAR(250) DEFAULT NULL,
  REQUEST_BY VARCHAR(50) DEFAULT NULL,
  DATE_REQUIREMENT DATE DEFAULT NULL,
  TIME VARCHAR(35) DEFAULT NULL,
  COMMUNICATION_STATUS VARCHAR(35) DEFAULT NULL,
  REQUEST_DETAILS TEXT DEFAULT NULL,
  FILE_NAME VARCHAR(35) NOT NULL DEFAULT '',
  HASH_VALUE VARCHAR(8000) NOT NULL DEFAULT '',
  UPDATED_BY VARCHAR(50) NOT NULL DEFAULT '',
  UPDATED_DT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  FLAG INT(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  INDEX Index_TS2 (DATE),
  FULLTEXT INDEX Index_TS3 (MEMBER_ME, CONSUMER_ME, ACCOUNT_NUMBER, FILE_NAME, OTHERS, HASH_VALUE)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 488
CHARACTER SET latin1
COLLATE latin1_swedish_ci;






--
-- Definition for table tb_transactions
--
DROP TABLE IF EXISTS tb_transactions;
CREATE TABLE tb_transactions (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  SR_NO VARCHAR(250) DEFAULT NULL,
  DATE DATE DEFAULT NULL,
  MEMBER_ME VARCHAR(250) DEFAULT NULL,
  CONSUMER_ME VARCHAR(250) DEFAULT NULL,
  ACCOUNT_NUMBER VARCHAR(250) DEFAULT NULL,
  ACCOUNT_TO_BE_SUPPRESSED VARCHAR(250) DEFAULT NULL,
  STATUS VARCHAR(35) DEFAULT NULL,
  COMMENTS TEXT DEFAULT NULL,
  OWNERSHIP_INDICATOR VARCHAR(250) DEFAULT NULL,
  ACCOUNT_TYPE VARCHAR(250) DEFAULT NULL,
  CURRENT_BALANCE VARCHAR(250) DEFAULT NULL,
  AMOUNT_OVERDUE VARCHAR(250) DEFAULT NULL,
  DATE_CLOSED DATE DEFAULT NULL,
  DATE_OF_LAST_PAYMENT DATE DEFAULT NULL,
  DATE_REPORTED DATE DEFAULT NULL,
  SACTIONED_AMOUNT VARCHAR(250) DEFAULT NULL,
  NDPD_FOR_LATEST_MONTH VARCHAR(250) DEFAULT NULL,
  ACCOUNT_STATUS VARCHAR(250) DEFAULT NULL,
  OTHERS VARCHAR(2000) DEFAULT NULL,
  RESPONSE VARCHAR(2000) DEFAULT NULL,
  DATE_PROCESSED DATE DEFAULT NULL,
  METHOD VARCHAR(250) DEFAULT NULL,
  MEMBER_CODE VARCHAR(250) DEFAULT NULL,
  REQUEST_BY VARCHAR(50) DEFAULT NULL,
  DATE_REQUIREMENT DATE DEFAULT NULL,
  TIME VARCHAR(35) DEFAULT NULL,
  COMMUNICATION_STATUS VARCHAR(35) DEFAULT NULL,
  REQUEST_DETAILS TEXT DEFAULT NULL,
  FILE_NAME VARCHAR(35) NOT NULL DEFAULT '',
  HASH_VALUE VARCHAR(8000) NOT NULL DEFAULT '',
  UPDATED_BY VARCHAR(50) NOT NULL DEFAULT '',
  UPDATED_DT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (ID),
  INDEX Index_T2 (DATE),
  FULLTEXT INDEX Index_T3 (MEMBER_ME, CONSUMER_ME, ACCOUNT_NUMBER, FILE_NAME, OTHERS, HASH_VALUE)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 945
CHARACTER SET latin1
COLLATE latin1_swedish_ci;








--
-- Definition for table tb_rejected_transactions
--
DROP TABLE IF EXISTS tb_rejected_transactions;
CREATE TABLE tb_rejected_transactions (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  SR_NO VARCHAR(250) DEFAULT NULL,
  DATE VARCHAR(250) DEFAULT NULL,
  MEMBER_ME VARCHAR(250) DEFAULT NULL,
  CONSUMER_ME VARCHAR(250) DEFAULT NULL,
  ACCOUNT_NUMBER VARCHAR(250) DEFAULT NULL,
  ACCOUNT_TO_BE_SUPPRESSED VARCHAR(250) DEFAULT NULL,
  STATUS VARCHAR(35) DEFAULT NULL,
  COMMENTS TEXT DEFAULT NULL,
  OWNERSHIP_INDICATOR VARCHAR(250) DEFAULT NULL,
  ACCOUNT_TYPE VARCHAR(250) DEFAULT NULL,
  CURRENT_BALANCE VARCHAR(250) DEFAULT NULL,
  AMOUNT_OVERDUE VARCHAR(250) DEFAULT NULL,
  DATE_CLOSED VARCHAR(250) DEFAULT NULL,
  DATE_OF_LAST_PAYMENT VARCHAR(250) DEFAULT NULL,
  DATE_REPORTED VARCHAR(250) DEFAULT NULL,
  SACTIONED_AMOUNT VARCHAR(250) DEFAULT NULL,
  NDPD_FOR_LATEST_MONTH VARCHAR(250) DEFAULT NULL,
  ACCOUNT_STATUS VARCHAR(250) DEFAULT NULL,
  OTHERS VARCHAR(2000) DEFAULT NULL,
  RESPONSE VARCHAR(2000) DEFAULT NULL,
  DATE_PROCESSED VARCHAR(250) DEFAULT NULL,
  METHOD VARCHAR(250) DEFAULT NULL,
  MEMBER_CODE VARCHAR(250) DEFAULT NULL,
  REQUEST_BY VARCHAR(50) DEFAULT NULL,
  DATE_REQUIREMENT VARCHAR(250) DEFAULT NULL,
  TIME VARCHAR(35) DEFAULT NULL,
  COMMUNICATION_STATUS VARCHAR(35) DEFAULT NULL,
  REQUEST_DETAILS LONGTEXT DEFAULT NULL,
  FILE_NAME VARCHAR(35) NOT NULL DEFAULT '',
  HASH_VALUE VARCHAR(8000) NOT NULL DEFAULT '',
  UPDATED_BY VARCHAR(50) NOT NULL DEFAULT '',
  UPDATED_DT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  FLAG INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 488
CHARACTER SET latin1
COLLATE latin1_swedish_ci;





--
-- Definition for table tb_lookup
--
DROP TABLE IF EXISTS tb_lookup;
CREATE TABLE tb_lookup (
  CODETYPE INT(10) NOT NULL,
  CODETYPE_DESCRIPTION VARCHAR(105) DEFAULT NULL,
  CODE_ID VARCHAR(35) NOT NULL,
  CODE_DESCRIPTION VARCHAR(105) DEFAULT NULL,
  PRIMARY KEY (CODETYPE, CODE_ID)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2048
CHARACTER SET latin1
COLLATE latin1_swedish_ci;



--
-- Definition for table tb_auditevent
--
DROP TABLE IF EXISTS tb_auditevent;
CREATE TABLE tb_auditevent (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  LOGIN_ID VARCHAR(50) NOT NULL DEFAULT '',
  MODULE_NAME VARCHAR(100) DEFAULT '',
  TIME_OF_ACCESS DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  ACTIVITY VARCHAR(30) DEFAULT '',
  IP_ADDRESS VARCHAR(100) DEFAULT '',
  REMARKS VARCHAR(2000) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 250
CHARACTER SET latin1
COLLATE latin1_swedish_ci;





